version: '2.4'

services:
  web:
    build: ./flask
    ports:
      - "5001:5000"
    volumes:
      - wb-data:/usr/src/app/data
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db-data:/var/lib/postgresql/data:delegated

volumes:
  db-data:
  wb-data: